// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: 'Home',
    },
    {
      type: 'category',
      label: 'MA 103 Calculus',
      collapsed: true,
      link: {
        type: 'generated-index',
        slug: 'ma103',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'MA 103 Calculus  of Single Variable and Linear Algebra',
        },
      ],
    },
    {
      type: 'category',
      label: 'MA 104 ODE',
      collapsed: true,
      link: {
        type: 'generated-index',
        slug: 'ma104',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'MA 104 Ordinary Differential Equations',
        },
      ],
    },
    {
      type: 'category',
      label: 'ES 119 Principles of AI',
      collapsed: true,
      link: {
        type: 'generated-index',
        slug: 'es119',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'ES119',
        },
      ],
    },
    {
      type: 'category',
      label: 'ES 114 Probability, Statistics and Data Visualisation',
      collapsed: true,
      link: {
        type: 'generated-index',
        slug: 'es114',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'ES 114 Probability, Statistics and Data Visualisation',
        },
      ],
    },
  ]
};

export default sidebars;
